export const ACTIONS = {
 ADD__DEVELOPER:"ADD__DEVELOPER",
 SHUFFLE:"SHUFFLE",
 ADD_NUMBER:"ADD_NUMBER",
 DEL_NUMBERS:"DEL_NUMBERS",
 RENAME:"RENAME",
 ADD_AGE:"ADD_AGE",
 DEL_BY_INDEX:"DEL_BY_INDEX"

}