const ACTIONS = {
  ADD_DEVELOPER: "ADD_DEVELOPER",
  SHUFFLE: "SHUFFLE",
  FILTER: "FILTER",
  ADD_NUMBER: "ADD_NUMBER",
  DELETE_NUMBER: "DELETE_NUMBER",
  CHANGE_NAME: "CHANGE_NAME",
  ADD_AGE: "ADD_AGE",
};

export default ACTIONS;
