 const ACTIONS = {
  ADD_DEVELOPER: 'ADD_DEVELOPER',
  SHUFFLE_ARRAY: 'SHUFFLE_ARRAY',
  ADD_RANDOM_NUMBER: 'ADD_RANDOM_NUMBER',
  DELETE_LESS_THAN_TEN: 'DELETE_LESS_THAN_TEN',
  CHANGE_USER_NAME: 'CHANGE_USER_NAME',
  ADD_USER_AGE: 'ADD_USER_AGE',
  DELETE_ARRAY_ELEMENT: 'DELETE_ARRAY_ELEMENT',
};
export default ACTIONS;