export {default as Home} from './Home/Home'
export {default as Blog} from './Blog/Blog'
export {default as Contact} from './Contact/Contact'
export {default as Team} from './Team/Team'
export {default as SingleBlog} from './SingleBlog/SingleBlog'
export {default as ErrorPage} from './ErrorPage/ErrorPage'
export {default as Products} from './Products/Products'