export { default as Home } from './home/Home'
export { default as Blog } from './Blog/Blog'
export { default as Contact } from './Contact/Contact'
export { default as About } from './About/About'
export { default as SingleBlog } from './SingleBlog/SingleBlog'
export { default as ErrorPage } from './ErrorPage/ErrorPage'