export { default as Home } from './Home/Home'
export { default as Blog } from './Blog/Blog'
export { default as Contact } from './Contact/Contact'
export { default as About } from './About/About'
export { default as SingleBlog } from './SingleBlog/SingleBlog'
export { default as SingleProduct } from './SingleProduct/SingleProduct'
export { default as Products } from './Products/Products'